[server]
runOnSave = true
maxUploadSize = 2048

[theme]
base="dark"
primaryColor = "#bc1077"
backgroundColor = "#14161a"
secondaryBackgroundColor = "#121317"
textColor = "#ebecf0"
font = "sans serif"
